-- Refresh the 50 theme-seeded simulations with richer, non-repetitive 5-round arcs.
-- This replaces rows generated by seed_simulator_50plus_from_themes.sql
-- (slugs ending with "-NN", where NN is 2 digits) while preserving the original 2 handcrafted sims.
--
-- Safe to re-run.

DO $$
DECLARE
  pid uuid;
  graph_themes text[];
  t text;
  i int;
  theme_label text;
  sim_slug text;
  sim_title text;
  sim_teaser text;
  sim_emoji text;
  display_base int := 200;
  rounds jsonb;
  context_line text;

  product_themes text[] := ARRAY[
    'Activation', 'Onboarding', 'Pricing', 'Retention', 'Roadmap',
    'User Research', 'Product-Market Fit', 'Segmentation', 'Funnel Friction', 'Quality'
  ];
  growth_themes text[] := ARRAY[
    'Acquisition', 'Distribution', 'Referrals', 'SEO', 'Monetization',
    'Lifecycle', 'Paid Channels', 'Content Loops', 'Conversion', 'Virality'
  ];
  strategy_themes text[] := ARRAY[
    'Market Timing', 'Positioning', 'Competitive Moats', 'Focus', 'Expansion',
    'Category Design', 'Portfolio Bets', 'Resource Allocation', 'Optionality', 'Risk'
  ];
  leadership_themes text[] := ARRAY[
    'Hiring', 'Decision Velocity', 'Team Alignment', 'Ownership', 'Feedback Culture',
    'Conflict Resolution', 'Manager Leverage', 'Org Design', 'Trust', 'Accountability'
  ];
  mixed_themes text[];
BEGIN
  SELECT id INTO pid
  FROM public.podcasts
  WHERE slug = 'lennys-podcast'
  LIMIT 1;

  IF pid IS NULL THEN
    RAISE NOTICE 'refresh_simulator_50plus_content: podcast lennys-podcast not found; skipping';
    RETURN;
  END IF;

  -- Remove only generated simulator rows (slugs like "...-01", "...-02", etc.)
  DELETE FROM public.simulation_definitions
  WHERE podcast_id = pid
    AND slug ~ '^[a-z0-9-]+-[0-9]{2}$'
    AND track IN ('product', 'growth', 'strategy', 'leadership', 'mixed');

  -- Pull theme labels from knowledge graph cache for mixed track.
  SELECT array_agg(DISTINCT trim(n->>'label'))
  INTO graph_themes
  FROM public.knowledge_graph_cache kgc
  CROSS JOIN LATERAL jsonb_array_elements(kgc.graph_data->'nodes') n
  WHERE kgc.podcast_slug = 'lennys-podcast'
    AND n->>'type' = 'theme'
    AND n ? 'label'
    AND length(trim(n->>'label')) > 0;

  IF graph_themes IS NULL OR array_length(graph_themes, 1) < 10 THEN
    mixed_themes := ARRAY[
      'Execution under uncertainty', 'Founder-operator mindset', 'High-stakes communication',
      'Shipping discipline', 'Cross-functional alignment', 'Tradeoff quality',
      'Compounding decisions', 'Learning velocity', 'Resilience', 'Strategic clarity'
    ];
  ELSE
    mixed_themes := graph_themes[1:10];
  END IF;

  FOREACH t IN ARRAY ARRAY['product', 'growth', 'strategy', 'leadership', 'mixed']
  LOOP
    FOR i IN 1..10
    LOOP
      IF t = 'product' THEN
        theme_label := product_themes[((i - 1) % array_length(product_themes, 1)) + 1];
        sim_emoji := '🧩';
        context_line := 'You lead product and must balance user value, speed, and technical reality.';
      ELSIF t = 'growth' THEN
        theme_label := growth_themes[((i - 1) % array_length(growth_themes, 1)) + 1];
        sim_emoji := '📈';
        context_line := 'You own growth and every move has CAC, conversion, and retention consequences.';
      ELSIF t = 'strategy' THEN
        theme_label := strategy_themes[((i - 1) % array_length(strategy_themes, 1)) + 1];
        sim_emoji := '🧭';
        context_line := 'You are making multi-quarter bets under uncertainty with limited resources.';
      ELSIF t = 'leadership' THEN
        theme_label := leadership_themes[((i - 1) % array_length(leadership_themes, 1)) + 1];
        sim_emoji := '🧠';
        context_line := 'You lead people and outcomes; trust and clarity are part of execution.';
      ELSE
        theme_label := mixed_themes[((i - 1) % array_length(mixed_themes, 1)) + 1];
        sim_emoji := '⚖️';
        context_line := 'You are in a cross-functional pressure cooker with product, growth, and team constraints.';
      END IF;

      sim_slug := format(
        '%s-%s-%s',
        t,
        regexp_replace(lower(theme_label), '[^a-z0-9]+', '-', 'g'),
        lpad(i::text, 2, '0')
      );

      sim_title := format(
        '%s: %s',
        CASE t
          WHEN 'product' THEN 'Product Decision Drill'
          WHEN 'growth' THEN 'Growth Pressure Test'
          WHEN 'strategy' THEN 'Strategy Bet Lab'
          WHEN 'leadership' THEN 'Leadership Decision Room'
          ELSE 'Mixed Challenge Arena'
        END,
        theme_label
      );

      sim_teaser := format(
        '%s Theme: %s. 5 decisions · real trade-offs · no obvious right answer.',
        context_line,
        theme_label
      );

      rounds := jsonb_build_array(
        jsonb_build_object(
          'prompt',
          format(
            '%s\n\nRound 1 — Diagnosis:\nEarly signals around "%s" are conflicting. Leadership wants a plan by tomorrow. What do you do first?',
            context_line, theme_label
          ),
          'choices',
          jsonb_build_array(
            jsonb_build_object(
              'id','a',
              'label','Publish a fast action memo with a provisional hypothesis',
              'feedback',jsonb_build_object('layer1','You created momentum quickly.','layer2','Risk: anchoring on weak signal.','layer3','Strong operators make assumptions explicit and reversible.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','Top guests often start with a clear, testable narrative before broad execution.','whatTheyDid',jsonb_build_array('Named core hypothesis','Set evidence bar'),'impact',jsonb_build_array('Faster alignment'),'videoUrl',NULL,'takeaway','Speed is strongest when assumptions are visible.'),
              'profileWeights',jsonb_build_object('speedVsDepth',0.25,'shortVsLong',0.15,'riskVsConviction',0.2),
              'citationQueryHint',format('Lennys podcast %s early signal diagnosis hypothesis setting', theme_label)
            ),
            jsonb_build_object(
              'id','b',
              'label','Run a 48-hour deep dive before committing direction',
              'feedback',jsonb_build_object('layer1','You optimized for diagnostic confidence.','layer2','Risk: perceived inaction.','layer3','Operators who delay commitment briefly often avoid costly whiplash.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','High-quality leaders repeatedly separate noise from trend before deploying large effort.','whatTheyDid',jsonb_build_array('Segmented cohorts','Validated instrumentation'),'impact',jsonb_build_array('Better decisions'),'videoUrl',NULL,'takeaway','Short diagnostic pauses can increase total velocity.'),
              'profileWeights',jsonb_build_object('speedVsDepth',-0.3,'shortVsLong',-0.2,'riskVsConviction',-0.1),
              'citationQueryHint',format('Lennys podcast %s cohort analysis before execution', theme_label)
            ),
            jsonb_build_object(
              'id','c',
              'label','Escalate to execs and request a top-down directive',
              'feedback',jsonb_build_object('layer1','You reduced local ambiguity quickly.','layer2','Risk: weaker ownership at team level.','layer3','Great operators escalate constraints, not accountability.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','In strong orgs, leaders ask for clarity while retaining decision ownership.','whatTheyDid',jsonb_build_array('Clarified decision rights','Kept local ownership'),'impact',jsonb_build_array('Less thrash'),'videoUrl',NULL,'takeaway','Escalate context, not responsibility.'),
              'profileWeights',jsonb_build_object('speedVsDepth',0.1,'shortVsLong',0.2,'riskVsConviction',0.25),
              'citationQueryHint',format('Lennys podcast %s decision ownership escalation', theme_label)
            )
          )
        ),
        jsonb_build_object(
          'prompt',
          format(
            'Round 2 — Prioritization:\nYou can fund only one path this sprint for "%s". Which lever gets resources now?',
            theme_label
          ),
          'choices',
          jsonb_build_array(
            jsonb_build_object(
              'id','a',
              'label','Immediate conversion lift with tactical changes',
              'feedback',jsonb_build_object('layer1','You optimized for near-term impact.','layer2','Risk: local max trap.','layer3','Operators tie short wins to longer strategic checks.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','Quick wins work best when paired with explicit guardrails.','whatTheyDid',jsonb_build_array('Defined counter-metrics','Set review checkpoint'),'impact',jsonb_build_array('Controlled acceleration'),'videoUrl',NULL,'takeaway','Short-term gains need anti-regret guardrails.'),
              'profileWeights',jsonb_build_object('speedVsDepth',0.2,'shortVsLong',0.25,'riskVsConviction',0.15),
              'citationQueryHint',format('Lennys podcast %s short term vs long term prioritization', theme_label)
            ),
            jsonb_build_object(
              'id','b',
              'label','Structural fix that compounds over multiple quarters',
              'feedback',jsonb_build_object('layer1','You chose durability.','layer2','Risk: slower visible progress.','layer3','Top operators intentionally absorb short-term noise for long-term leverage.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','Durable systems are often built in quieter windows, not announcement moments.','whatTheyDid',jsonb_build_array('Protected core roadmap','Aligned long-run metric'),'impact',jsonb_build_array('Compounding outcomes'),'videoUrl',NULL,'takeaway','Compounding is a strategic choice.'),
              'profileWeights',jsonb_build_object('speedVsDepth',-0.25,'shortVsLong',-0.3,'riskVsConviction',-0.1),
              'citationQueryHint',format('Lennys podcast %s long term compounding product growth', theme_label)
            ),
            jsonb_build_object(
              'id','c',
              'label','Split budget across two bets to preserve optionality',
              'feedback',jsonb_build_object('layer1','You increased option coverage.','layer2','Risk: diluted focus.','layer3','Operators run parallel bets only with strict kill criteria.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','Portfolio logic works when stop-rules are precommitted.','whatTheyDid',jsonb_build_array('Set kill criteria','Time-boxed parallel bets'),'impact',jsonb_build_array('Faster learning'),'videoUrl',NULL,'takeaway','Optionality without discipline becomes drift.'),
              'profileWeights',jsonb_build_object('speedVsDepth',0.1,'shortVsLong',0.05,'riskVsConviction',0.25),
              'citationQueryHint',format('Lennys podcast %s portfolio bets optionality stop rules', theme_label)
            )
          )
        ),
        jsonb_build_object(
          'prompt',
          format(
            'Round 3 — Stakeholder tension:\nSales, product, and finance disagree on what success in "%s" means. You have one meeting to reset the room.',
            theme_label
          ),
          'choices',
          jsonb_build_array(
            jsonb_build_object(
              'id','a',
              'label','Set one shared metric contract for all teams',
              'feedback',jsonb_build_object('layer1','You created cross-functional clarity.','layer2','Risk: misses useful local nuance.','layer3','High-performing teams align on one truth, then tune local levers.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','A common scorecard often unlocks decision velocity across teams.','whatTheyDid',jsonb_build_array('Aligned definitions','Ritualized reviews'),'impact',jsonb_build_array('Fewer politics'),'videoUrl',NULL,'takeaway','Shared definitions are execution infrastructure.'),
              'profileWeights',jsonb_build_object('speedVsDepth',0.2,'shortVsLong',0.1,'riskVsConviction',0.15),
              'citationQueryHint',format('Lennys podcast %s metric contract cross functional alignment', theme_label)
            ),
            jsonb_build_object(
              'id','b',
              'label','Run a two-week alignment sprint before resetting targets',
              'feedback',jsonb_build_object('layer1','You invested in long-term execution quality.','layer2','Risk: short-term frustration.','layer3','Operators often treat alignment debt as the hidden bottleneck.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','When teams use different realities, shipping faster rarely helps.','whatTheyDid',jsonb_build_array('Mapped assumptions','Resolved conflicting incentives'),'impact',jsonb_build_array('Cleaner execution'),'videoUrl',NULL,'takeaway','Alignment work is product work.'),
              'profileWeights',jsonb_build_object('speedVsDepth',-0.2,'shortVsLong',-0.15,'riskVsConviction',-0.05),
              'citationQueryHint',format('Lennys podcast %s alignment debt and incentives', theme_label)
            ),
            jsonb_build_object(
              'id','c',
              'label','Keep team-specific KPIs but enforce one monthly sync',
              'feedback',jsonb_build_object('layer1','You protected local autonomy.','layer2','Risk: delayed conflict detection.','layer3','Great operators decentralize tactics, not objective reality.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','Autonomy scales best when teams share non-negotiable constraints.','whatTheyDid',jsonb_build_array('Set common constraints','Kept local flexibility'),'impact',jsonb_build_array('Balanced speed + ownership'),'videoUrl',NULL,'takeaway','Autonomy needs boundaries.'),
              'profileWeights',jsonb_build_object('speedVsDepth',0.05,'shortVsLong',0.2,'riskVsConviction',0.2),
              'citationQueryHint',format('Lennys podcast %s autonomy with constraints leadership', theme_label)
            )
          )
        ),
        jsonb_build_object(
          'prompt',
          format(
            'Round 4 — Execution constraint:\nYou lose 30%% engineering capacity this month while "%s" goals remain unchanged. What is your move?',
            theme_label
          ),
          'choices',
          jsonb_build_array(
            jsonb_build_object(
              'id','a',
              'label','Cut scope aggressively and preserve momentum',
              'feedback',jsonb_build_object('layer1','You protected shipping tempo.','layer2','Risk: hidden debt accumulation.','layer3','Operators do this well when they predefine follow-up cleanup.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','Scope cuts are powerful when paired with explicit debt paydown windows.','whatTheyDid',jsonb_build_array('Named must-haves','Scheduled debt pass'),'impact',jsonb_build_array('Maintained cadence'),'videoUrl',NULL,'takeaway','Shrink scope, not standards.'),
              'profileWeights',jsonb_build_object('speedVsDepth',0.3,'shortVsLong',0.2,'riskVsConviction',0.1),
              'citationQueryHint',format('Lennys podcast %s scope cuts with quality guardrails', theme_label)
            ),
            jsonb_build_object(
              'id','b',
              'label','Freeze new bets and fix the highest-risk foundations',
              'feedback',jsonb_build_object('layer1','You prioritized risk reduction.','layer2','Risk: near-term narrative weakens.','layer3','Strong operators choose this when downside asymmetry is high.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','Quiet foundational work often unlocks future velocity.','whatTheyDid',jsonb_build_array('Prioritized systemic risk','Protected deep work'),'impact',jsonb_build_array('Lower volatility'),'videoUrl',NULL,'takeaway','Resilience is a growth strategy.'),
              'profileWeights',jsonb_build_object('speedVsDepth',-0.3,'shortVsLong',-0.25,'riskVsConviction',-0.1),
              'citationQueryHint',format('Lennys podcast %s foundation work under constraints', theme_label)
            ),
            jsonb_build_object(
              'id','c',
              'label','Re-negotiate goals upward in uncertainty narrative',
              'feedback',jsonb_build_object('layer1','You attempted to preserve ambition through story.','layer2','Risk: credibility loss if outcomes miss.','layer3','Best operators tie narrative shifts to explicit operating changes.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','Narrative earns trust only when it changes decision behavior, not just messaging.','whatTheyDid',jsonb_build_array('Linked story to plan','Published checkpoint cadence'),'impact',jsonb_build_array('Higher trust when consistent'),'videoUrl',NULL,'takeaway','Story must tighten execution.'),
              'profileWeights',jsonb_build_object('speedVsDepth',0.1,'shortVsLong',0.2,'riskVsConviction',0.3),
              'citationQueryHint',format('Lennys podcast %s strategy narrative execution credibility', theme_label)
            )
          )
        ),
        jsonb_build_object(
          'prompt',
          format(
            'Round 5 — Final commitment:\nYou get one operating principle for the next 30 days on "%s". Which principle do you defend?',
            theme_label
          ),
          'choices',
          jsonb_build_array(
            jsonb_build_object(
              'id','a',
              'label','One bottleneck, one owner, one weekly review',
              'feedback',jsonb_build_object('layer1','You selected disciplined focus.','layer2','Risk: lower flexibility if context shifts quickly.','layer3','Operators with consistent review rhythm usually compound faster.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','Cadence and ownership are repeat patterns in high-quality operating systems.','whatTheyDid',jsonb_build_array('Named single bottleneck','Assigned clear owner'),'impact',jsonb_build_array('Compounding execution'),'videoUrl',NULL,'takeaway','Rhythm can be your moat.'),
              'profileWeights',jsonb_build_object('speedVsDepth',-0.1,'shortVsLong',-0.2,'riskVsConviction',0.0),
              'citationQueryHint',format('Lennys podcast %s weekly operating cadence ownership', theme_label)
            ),
            jsonb_build_object(
              'id','b',
              'label','Max experiment throughput with hard stop rules',
              'feedback',jsonb_build_object('layer1','You optimized for learning velocity.','layer2','Risk: context switching fatigue.','layer3','Great operators pair volume with ruthless pruning.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','High-tempo teams win when they kill weak bets early and visibly.','whatTheyDid',jsonb_build_array('Ran many small tests','Killed losers fast'),'impact',jsonb_build_array('Faster discovery'),'videoUrl',NULL,'takeaway','Experimentation needs subtraction.'),
              'profileWeights',jsonb_build_object('speedVsDepth',0.25,'shortVsLong',0.15,'riskVsConviction',0.2),
              'citationQueryHint',format('Lennys podcast %s experimentation cadence stop rules', theme_label)
            ),
            jsonb_build_object(
              'id','c',
              'label','Protect team attention by cutting low-leverage work',
              'feedback',jsonb_build_object('layer1','You treated attention as a scarce strategic asset.','layer2','Risk: saying no can create short-term friction.','layer3','Top operators know leverage often comes from subtraction.'),
              'layer4_static',jsonb_build_object('headline','How real operators approached this','operatorLine','Saying no is frequently the highest-leverage operating decision.','whatTheyDid',jsonb_build_array('Removed low ROI work','Reallocated focus to core loop'),'impact',jsonb_build_array('Higher leverage outcomes'),'videoUrl',NULL,'takeaway','Focus is strategy in executable form.'),
              'profileWeights',jsonb_build_object('speedVsDepth',-0.2,'shortVsLong',-0.1,'riskVsConviction',0.1),
              'citationQueryHint',format('Lennys podcast %s saying no and focus leverage', theme_label)
            )
          )
        )
      );

      INSERT INTO public.simulation_definitions (
        podcast_id,
        slug,
        track,
        title,
        teaser,
        cover_emoji,
        rounds,
        estimated_minutes,
        published,
        display_order
      )
      VALUES (
        pid,
        sim_slug,
        t,
        sim_title,
        sim_teaser,
        sim_emoji,
        rounds,
        8,
        true,
        display_base
        + CASE t
            WHEN 'product' THEN 0
            WHEN 'growth' THEN 100
            WHEN 'strategy' THEN 200
            WHEN 'leadership' THEN 300
            ELSE 400
          END
        + i
      )
      ON CONFLICT (podcast_id, slug) DO NOTHING;
    END LOOP;
  END LOOP;

  RAISE NOTICE 'refresh_simulator_50plus_content: completed';
END $$;"}}}
