'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import Footer from '@/components/Footer'

export default function TermsOfServicePage() {
  const router = useRouter()

  return (
    <div className="min-h-screen w-full bg-cream-50">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-cream-50/80 backdrop-blur-lg border-b border-charcoal-200/50">
        <div className="max-w-4xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <button
              onClick={() => router.push('/')}
              className="flex items-center gap-2 group"
            >
              <img src="/espresso-logo.png" alt="espresso" className="w-6 h-6 object-contain" />
              <span className="text-lg font-serif font-semibold text-charcoal-900 group-hover:text-charcoal-700 transition-colors">
                espresso
              </span>
            </button>
            <button
              onClick={() => router.back()}
              className="text-sm font-medium text-charcoal-700 hover:text-charcoal-900 transition-colors"
            >
              ← Back
            </button>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-12 md:py-16">
        <article className="bg-white rounded-2xl shadow-sm border border-charcoal-100 p-8 md:p-12">
          <h1 className="text-4xl md:text-5xl font-bold text-charcoal-900 mb-4">
            Terms of Service
          </h1>
          <p className="text-sm text-charcoal-500 mb-8">
            Last Updated: February 9, 2026
          </p>

          {/* Experimental Notice */}
          <div className="mb-8 p-4 bg-red-50 border-l-4 border-red-500 rounded-r-lg">
            <p className="text-sm font-semibold text-charcoal-900 mb-2">🚨 IMPORTANT NOTICE</p>
            <p className="text-sm text-charcoal-700 leading-relaxed mb-2">
              espresso is a <strong>FREE, experimental, educational, non-commercial project</strong> by an individual developer.
            </p>
            <p className="text-sm text-charcoal-700 leading-relaxed">
              <strong>ALL podcast content belongs to its original creators.</strong> We claim NO ownership or rights. 
              Use at your own risk.
            </p>
          </div>

          <div className="prose max-w-none">
            {/* Acceptance */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-charcoal-700 leading-relaxed">
                By accessing or using espresso (the &quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Service.
              </p>
            </section>

            {/* Description */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">2. Description of Service</h2>
              <p className="text-charcoal-700 mb-3">espresso is an AI-powered service that allows users to:</p>
              <ul className="list-disc pl-6 space-y-2 text-charcoal-700 mb-4">
                <li>Explore synthesized concepts and knowledge bases from podcast transcripts</li>
                <li>Ask questions and receive AI-generated responses grounded in transcript evidence</li>
                <li>Browse curated insights organized by podcast, topic, and guest</li>
                <li>Request new knowledge bases for podcasts and thought leaders</li>
              </ul>

              <div className="bg-cream-100 border-l-4 border-charcoal-400 p-4">
                <p className="font-semibold text-charcoal-900 mb-2">Important Disclaimers:</p>
                <ul className="list-disc pl-6 space-y-2 text-charcoal-700">
                  <li><strong>AI-Generated Content</strong>: All responses are generated by AI models and may contain inaccuracies</li>
                  <li><strong>Not Professional Advice</strong>: Responses do not constitute professional, legal, financial, or medical advice</li>
                  <li><strong>Educational Purpose</strong>: The Service is for informational purposes only</li>
                  <li><strong>Source Material</strong>: Content is derived from publicly available podcast transcripts</li>
                </ul>
              </div>
            </section>

            {/* Eligibility */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">3. Eligibility</h2>
              <p className="text-charcoal-700">
                You must be at least 13 years old to use this Service. By using the Service, you represent and warrant that you meet this age requirement.
              </p>
            </section>

            {/* Account Registration */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">4. Account Registration</h2>
              
              <h3 className="text-xl font-semibold text-charcoal-800 mb-3">Creating an Account</h3>
              <p className="text-charcoal-700 mb-3">To use certain features, you must create an account by providing:</p>
              <ul className="list-disc pl-6 space-y-2 text-charcoal-700 mb-4">
                <li>A valid email address</li>
                <li>A secure password</li>
                <li>Your name</li>
              </ul>

              <h3 className="text-xl font-semibold text-charcoal-800 mb-3">Account Security</h3>
              <p className="text-charcoal-700 mb-3">You are responsible for:</p>
              <ul className="list-disc pl-6 space-y-2 text-charcoal-700 mb-4">
                <li>Maintaining the confidentiality of your password</li>
                <li>All activities that occur under your account</li>
                <li>Notifying us immediately of any unauthorized access</li>
              </ul>
            </section>

            {/* Acceptable Use */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">5. Acceptable Use</h2>
              
              <h3 className="text-xl font-semibold text-charcoal-800 mb-3">You Agree To:</h3>
              <ul className="list-disc pl-6 space-y-2 text-charcoal-700 mb-4">
                <li>Use the Service for lawful purposes only</li>
                <li>Provide accurate account information</li>
                <li>Respect the intellectual property rights of others</li>
                <li>Use the Service in accordance with applicable laws</li>
              </ul>

              <h3 className="text-xl font-semibold text-charcoal-800 mb-3">You Agree NOT To:</h3>
              <ul className="list-disc pl-6 space-y-2 text-charcoal-700 mb-4">
                <li>Attempt to bypass security measures or reverse engineer the Service</li>
                <li>Use automated tools (bots, scrapers) without permission</li>
                <li>Present AI responses as your own work without disclosure</li>
                <li>Rely on AI responses for critical decisions without verification</li>
                <li>Harass, threaten, or harm others</li>
                <li>Upload malicious code or viruses</li>
                <li>Impersonate others or misrepresent your affiliation</li>
                <li>Use the Service for illegal purposes</li>
              </ul>
            </section>

            {/* Intellectual Property */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">6. Intellectual Property</h2>
              
              <h3 className="text-xl font-semibold text-charcoal-800 mb-3">Our Rights</h3>
              <p className="text-charcoal-700 mb-4">
                The Service, including all content and functionality, is owned by espresso and is protected by copyright, trademark, and other intellectual property laws.
              </p>

              <h3 className="text-xl font-semibold text-charcoal-800 mb-3">Source Material</h3>
              <ul className="list-disc pl-6 space-y-2 text-charcoal-700 mb-4">
                <li>Podcast transcripts are sourced from publicly available content</li>
                <li>Original podcast content belongs to the respective creators</li>
                <li>We claim no ownership over the original podcast content</li>
              </ul>

              <h3 className="text-xl font-semibold text-charcoal-800 mb-3">AI-Generated Content</h3>
              <p className="text-charcoal-700 mb-3">You may use AI-generated responses for personal, non-commercial purposes. If sharing publicly, you should:</p>
              <ul className="list-disc pl-6 space-y-2 text-charcoal-700 mb-4">
                <li>Disclose that it was AI-generated</li>
                <li>Attribute the source material (e.g., &quot;Based on Lenny&apos;s Podcast transcripts via espresso&quot;)</li>
                <li>Verify accuracy before relying on it</li>
              </ul>
            </section>

            {/* AI Model Providers */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">7. AI Model Providers</h2>
              <p className="text-charcoal-700 mb-3">The Service uses third-party AI models:</p>
              <ul className="list-disc pl-6 space-y-2 text-charcoal-700 mb-4">
                <li><strong>Google Gemini</strong>: Subject to Google&apos;s Terms of Service</li>
                <li><strong>OpenAI</strong>: Subject to OpenAI&apos;s Terms of Service</li>
              </ul>
              <p className="text-charcoal-700">
                Your queries may be sent to these providers. Please review their terms and privacy policies.
              </p>
            </section>

            {/* Disclaimers */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">8. Disclaimers and Limitations</h2>
              
              <div className="bg-cream-100 border-l-4 border-charcoal-400 p-4 mb-4">
                <h3 className="text-lg font-semibold text-charcoal-900 mb-2">No Warranty</h3>
                <p className="text-charcoal-700 mb-3">
                  THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, INCLUDING:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-charcoal-700">
                  <li>Warranties of merchantability or fitness for a particular purpose</li>
                  <li>Warranties that the Service will be uninterrupted or error-free</li>
                  <li>Warranties regarding the accuracy of AI-generated content</li>
                </ul>
              </div>

              <div className="bg-red-50 border-l-4 border-red-500 p-4">
                <h3 className="text-lg font-semibold text-charcoal-900 mb-2">Limitation of Liability</h3>
                <p className="text-charcoal-700 mb-3">
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, espresso SHALL NOT BE LIABLE FOR:
                </p>
                <ul className="list-disc pl-6 space-y-2 text-charcoal-700">
                  <li>Any indirect, incidental, special, or consequential damages</li>
                  <li>Loss of profits, data, or goodwill</li>
                  <li>Damages from your use or inability to use the Service</li>
                  <li>Damages from reliance on AI-generated content</li>
                </ul>
                <p className="text-charcoal-700 mt-3">
                  <strong>Our total liability shall not exceed $100</strong> or the amount you paid (if any), whichever is greater.
                </p>
              </div>
            </section>

            {/* AI Content Accuracy */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">9. AI Content Accuracy and Responsibility</h2>
              
              <h3 className="text-xl font-semibold text-charcoal-800 mb-3">No Guarantee of Accuracy</h3>
              <ul className="list-disc pl-6 space-y-2 text-charcoal-700 mb-4">
                <li>AI-generated responses may be incorrect, incomplete, or misleading</li>
                <li>Responses are based on podcast transcripts and may not reflect current information</li>
                <li>We do not verify the accuracy of AI-generated content</li>
              </ul>

              <h3 className="text-xl font-semibold text-charcoal-800 mb-3">Your Responsibility</h3>
              <p className="text-charcoal-700 mb-3">You are solely responsible for:</p>
              <ul className="list-disc pl-6 space-y-2 text-charcoal-700 mb-4">
                <li>Verifying the accuracy of AI-generated responses</li>
                <li>Any decisions you make based on AI-generated content</li>
                <li>Any harm resulting from reliance on AI-generated content</li>
              </ul>
            </section>

            {/* Termination */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">10. Termination</h2>
              <p className="text-charcoal-700 mb-3">
                We may suspend or terminate your access if you violate these Terms or if your use poses a security risk.
              </p>
              <p className="text-charcoal-700">
                You may stop using the Service and delete your account at any time by contacting <a href="mailto:somshivanshu@gmail.com" className="text-charcoal-800 underline underline-offset-2 hover:text-charcoal-600 transition-colors">somshivanshu@gmail.com</a>
              </p>
            </section>

            {/* Contact */}
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-charcoal-900 mb-4">11. Contact Information</h2>
              <p className="text-charcoal-700">
                If you have questions about these Terms, contact us at: <a href="mailto:somshivanshu@gmail.com" className="text-charcoal-800 underline underline-offset-2 hover:text-charcoal-600 transition-colors">somshivanshu@gmail.com</a>
              </p>
            </section>

            {/* Summary */}
            <section className="bg-charcoal-50 rounded-lg p-6 border border-charcoal-200">
              <h2 className="text-xl font-bold text-charcoal-900 mb-4">Summary (TL;DR)</h2>
              
              <div className="space-y-4 text-charcoal-700">
                <div>
                  <p className="font-semibold mb-2">What you can do:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Explore knowledge bases and ask questions</li>
                    <li>Use responses for personal learning</li>
                    <li>Create an account with email/name</li>
                  </ul>
                </div>

                <div>
                  <p className="font-semibold mb-2">What you can&apos;t do:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Abuse the service or try to hack it</li>
                    <li>Present AI responses as guaranteed truth</li>
                    <li>Use for illegal purposes</li>
                    <li>Rely on responses for critical decisions</li>
                  </ul>
                </div>

                <div>
                  <p className="font-semibold mb-2">Important to know:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>AI responses may be inaccurate</li>
                    <li>This is NOT professional advice</li>
                    <li>We can change or discontinue the service</li>
                    <li>You&apos;re responsible for how you use AI content</li>
                  </ul>
                </div>

                <div>
                  <p className="font-semibold mb-2">We&apos;re not liable for:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Inaccurate AI responses</li>
                    <li>Decisions you make based on content</li>
                    <li>Service interruptions</li>
                  </ul>
                </div>
              </div>
            </section>

            <div className="mt-8 p-4 bg-charcoal-50 border border-charcoal-200 rounded-lg">
              <p className="text-charcoal-900 font-semibold">
                BY USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE.
              </p>
            </div>
          </div>
        </article>
      </main>

      <Footer />
    </div>
  )
}
